### ISSUE TITLE
Another case of wrong tile placement.

### ISSUE THREAD

**Issue by Joao-Victor-Bonfim** [SolariusScorch/XComFiles#102]
EXALT HQ type map
![screen001](https://user-images.githubusercontent.com/23298617/83365090-1c0b5b80-a37c-11ea-9c35-4a1cb3ada4c3.png)

**Comment by SolariusScorch** [comment]
Sorry, where? Can't see anything at a glance.

**Comment by Joao-Victor-Bonfim** [comment]
> 
> 
> Sorry, where? Can't see anything at a glance.

My soldier is on the top of the stairs, yet, there is a tile right over it.
Basically the topmost piece of stairs is covered with a tile.

**Comment by SolariusScorch** [comment]
Fixed!
Thank you.
