### ISSUE TITLE
Translation platform

### ISSUE THREAD

**Issue by buhtz** [SolariusScorch/XComFiles#178]
How can someone contribute translations?
Do you use a translation platform like Weblate or something?

**Comment by buhtz** [comment]
Hello?

**Comment by SolariusScorch** [comment]
Sorry, I missed your earlier message.
Yes, XCF uses Transifex: https://app.transifex.com/openxcom/openxcom-mods/xcf/
You will need to register an account, but it's free and should be painless.
Which language would you like to work on?

**Comment by buhtz** [comment]
I would try German.
I suggest to mention this information in your README.md.

Transifex? No body is perfect. :laughing:

**Comment by SolariusScorch** [comment]
Very well, I have added this info in README.md and X-Com_Files_readme.txt.

> Transifex? No body is perfect. 😆
Sorry, that's what the whole OXC is using, as well as OpenApoc. :) My experience with it is mostly positive, though.

**Comment by buhtz** [comment]
My concerns about Transifex are more grounded in ideological reasons. Technically I didn't have heard something bad about it.

I have some questions about translation.

- Do you have someone like a "German translations maintainer"?
- There are unreviewed strings but I am not able to review/approve them?
- When I add "comments" or "issues" to a specific string how is notified about it?
- Screenshots are missing. And I can not see an option to add screenshots. I would add some.

Some of the German translations are IMHO stupid and kind of embarrassing funny. That is why I ask about a "German translation maintainer". How does approve that?

One suggestion:
I know GNU gettext from Python context. I don't know how this works in a C/C++ environment.
But IMHO it would help if you would treat numbered names (e.g. "Spacer I", "Spacer II", "Spacer III", ...) as one term only.

In Python I would do it like this:

    SPACER_BASE_STR = _('Spacer')  # <-- That is a translatable string!
    for idx in ['I', 'II', 'III', 'IV', 'V', 'VI']:
        print(f'{SPACER_BASE_STR} {idx}')

This would reduce the amount of strings to translate from (in most cases?) 10 to 1 per entity.

**Comment by SolariusScorch** [comment]
1. There is no German translations maintainer.
2. I'm not sure why you have no access, perhaps you need to apply? I can investigate if you like.
3. That's a lot of ideas, sadly they're divorced from what Transifex does. Also, they're divorced from the OXC code.
4. No, I'm not removing any languages from Transifex, are you fucking insane?
