### ISSUE TITLE
Melee does not detect target correctly. in this case Dogs bite

### ISSUE THREAD

**Issue by greensalt99** [SolariusScorch/XComFiles#181]
![flowers](https://github.com/SolariusScorch/XComFiles/assets/154023649/1186b615-b44f-4bca-9915-de0490b2abac)

Hey Solarius Scorch, i dont know much about how dogs bite implemented.
dog attacks flowers but cant attack 2x2 enemy. tried diagonally too, and from other spot. those flowers somehow bugs it.

**Comment by greensalt99** [comment]
i might see wrong solutions for this problem, sorry Solarius. You know better how to improve code.

**Comment by greensalt99** [comment]
i can add x-comrat to this list.
Rat standing on grass and cant detect solder in front, all angles. NPC is not on grass, not damaged terrain. sorry forgot foto.

**Comment by SolariusScorch** [comment]
It's a common problem... And not really a bug, but a natural consequence of how the game's physics work.
The only way to solve this would be to make the dog as tall as a Sectoid, which would create new problems (like enemies being able to hit a dog which should be completely obscured by low cover).
Annoying as it is, I'm not really able to solve it in a satisfactory way.

**Comment by greensalt99** [comment]
sad :(
