### ISSUE TITLE
Missing instructions about download and installation

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [SolariusScorch/XComFiles#54]
The mod-section of the openxcom-forum is the first play to go about questions like this.

But the xcomfiles sub-forum contains no informations about a Download link or Installation instructions. Even this git-repo is not mentioned there on a central place.

And there is also [confusion about OXCE(+)](https://openxcom.org/forum/index.php/topic,7723.0.html). What is it, where to find, and do I really need it anymore. If you mention OXCE in your README.md file you should also provide a link to that project.

**Comment by SolariusScorch** [comment]
Hello,
Sorry it took me ages to notice this.
I added an installation link to the OXCE and the Git repo. Please let me know if this is fine.
best regards,
Solar
