### ISSUE TITLE
Rat breeding

### ISSUE THREAD

**Issue by Joao-Victor-Bonfim** [SolariusScorch/XComFiles#96]
I noticed that rat breeding costs elerium, even though you can easily get it in promotion 2, maybe make so it costs energetic blood plasma instead, since it is accessible at that point, there are few uses for it currently, it just stockpiles with ease on storage 😄, the blood plasma cost would be the same (1 blood plasma for a living rat = 1 elerium = 1 blood plasma from living giant rat) and it could be explained in flavour text that they need a high energy diet to reproduce, that would come from the blood plasma.

**Comment by SolariusScorch** [comment]
OK, makes sense. Done!
